### PR TITLE
Remove Rex as a dependency of msfrpc-client

### PR DESCRIPTION
**Pull request by busterb**
See https://github.com/rapid7/metasploit-framework/issues/9440

This removes Rex as a dependency of msfrpc-client, since the 'monolith' rex gem is now out-of-date compared to the code built into metasploit-framework, causing conflicts in vanilla Kali and ParrotSec due to how the gems and ruby are configured in those environments.

This switches to using Ruby standard libs, which are more than enough here. Lightly-tested, will possibly need @bcoles to judge if I broke anything that BeEF is using.

### CODE REVIEW

**Comment by busterb** [comment]
Interestingly, it's less code to use standard Ruby over Rex here.

**Comment by bcoles** [comment]
I wouldn't worry too much about BeEF. I'll cross that bridge when I get to it.

**Comment by bcoles** [comment]
Not sure if specifying `.ruby-version` of `2.5.1` will cause problems for BeEF. It's still on 2.4.x; with 2.5.x largely untested.

**Comment by busterb** [comment]
.ruby-version is a hint to RVM, but does not change the base requirements, which would be indicated in the gemspec file. This gem appears to have no minimum Ruby requirement at all currently.

**Comment by bcoles** [comment]
`.ruby-version` also applies to rbenv, which will automatically switch to the specified Ruby version - without warning.

However I believe your assertion is correct.

**Pull request merged**
